### ISSUE TITLE
Netbeans Plugin version not working with Netbeans 8.2

### ISSUE THREAD

**Issue by PowerUser1234** [amelentev/java-oo#55] opened 2018-03-30 05:39 UTC
Note: Injecting OO to javac

An annotation processor threw an uncaught exception.
Consult the following stack trace for details.
java.lang.IllegalArgumentException: Can not set com.sun.tools.javac.api.MultiTaskListener field com.sun.tools.javac.main.JavaCompiler.taskListener to javaoo.javac.OOProcessor$WaitAnalyzeTaskListener
	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:167)
	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:171)
	at sun.reflect.UnsafeObjectFieldAccessorImpl.set(UnsafeObjectFieldAccessorImpl.java:81)
	at java.lang.reflect.Field.set(Field.java:764)
	at javaoo.javac.OOProcessor.set(OOProcessor.java:102)
	at javaoo.javac.OOProcessor.init(OOProcessor.java:53)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment$ProcessorState.<init>(JavacProcessingEnvironment.java:500)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment$DiscoveredProcessors$ProcessorStateIterator.next(JavacProcessingEnvironment.java:597)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:690)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1800(JavacProcessingEnvironment.java:91)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1035)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1176)
	at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1170)
	at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:856)
	at com.sun.tools.javac.main.Main.compile(Main.java:523)
	at com.sun.tools.javac.main.Main.compile(Main.java:381)
	at com.sun.tools.javac.main.Main.compile(Main.java:370)
	at com.sun.tools.javac.main.Main.compile(Main.java:361)
	at com.sun.tools.javac.Main.compile(Main.java:56)
	at com.sun.tools.javac.Main.main(Main.java:42)
C:\Users\User\Desktop\Arbitrary Numbers\nbproject\build-impl.xml:955: The following error occurred while executing this line:
C:\Users\User\Desktop\Arbitrary Numbers\nbproject\build-impl.xml:295: Compile failed; see the compiler error output for details.
BUILD FAILED (total time: 0 seconds)

**Comment by amelentev** [comment] 2018-04-03 17:36
yes. netbeans 7.4+ uses modified javac and javaoo doesn't work with it yet.
duplicate of #15

**Closed by amelentev** 2018-04-03 17:36 UTC
Labels: duplicate
